### ISSUE TITLE
Out of space

### ISSUE THREAD

**Issue by lminer** [jjangsangy/MacOS-TensorflowBuilds#1]
I can't download the wheels because the repo is out of space.

**Comment by jjangsangy** [comment]
Thanks for notifying me on this.

I've put the binaries in separate releases that you can access here.

* [Tensorflow v1.3.1](https://github.com/jjangsangy/MacOS-TensorflowBuilds/releases/tag/v1.3.1)
* [Tensorflow v1.4.0rc0](https://github.com/jjangsangy/MacOS-TensorflowBuilds/releases/tag/1.4.0rc0)
